### ISSUE TITLE
Accept bzip2 compressed dumps

### ISSUE THREAD

**Issue by tobias-pook** [dmwm/DMWMMON#40]
It seems like spacemon does not accept bzip2 compressed files as produced by the chimera_dump script.

We extract the dumps on our phedex node now, but it would be nice to skip this step.

thanks,
Tobias

**Comment by nataliaratnikova** [comment]
Hi Tobias,
thanks for reporting. Could you make one of the chimera-dump produced dumps available to me: natasha at fnal gov .  Some temporary area on lxplus or on the grid accessible storage. So I can reproduce and fix the issue. 
Natalia .

**Comment by tobias-pook** [comment]
I sent a mail with a srm path to natasha at fnal gov .

**Comment by nataliaratnikova** [comment]
Hi Tobias,
thanks for the dump. I  reproduced  and fixed the problem, it did not show up in my tests with a small test dump. Let me know if  the fix : https://github.com/dmwm/DMWMMON/commit/a65e3747ebb57925e48390b83ab99e2f698d5d48 
 works for you.  I will then include it  in the next client update. 
Natalia

**Comment by nataliaratnikova** [comment]
Fixed in commit a65e3747ebb57925e48390b83ab99e2f698d5d48
